///
/// Derivee-Swift-Cxx-Bridge.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

// Forward declarations of C++ defined types
// Forward declaration of `HybridHybridTrackingSpec` to properly resolve imports.
namespace margelo::nitro::hybridtracker { class HybridHybridTrackingSpec; }

// Forward declarations of Swift defined types
// Forward declaration of `HybridHybridTrackingSpec_cxx` to properly resolve imports.
namespace Derivee { class HybridHybridTrackingSpec_cxx; }

// Include C++ defined types
#include "HybridHybridTrackingSpec.hpp"
#include <NitroModules/Result.hpp>
#include <exception>
#include <functional>
#include <memory>
#include <string>
#include <vector>

/**
 * Contains specialized versions of C++ templated types so they can be accessed from Swift,
 * as well as helper functions to interact with those C++ types from Swift.
 */
namespace margelo::nitro::hybridtracker::bridge::swift {

  // pragma MARK: std::function<void(const std::string& /* h3Index */)>
  /**
   * Specialized version of `std::function<void(const std::string&)>`.
   */
  using Func_void_std__string = std::function<void(const std::string& /* h3Index */)>;
  /**
   * Wrapper class for a `std::function<void(const std::string& / * h3Index * /)>`, this can be used from Swift.
   */
  class Func_void_std__string_Wrapper final {
  public:
    explicit Func_void_std__string_Wrapper(std::function<void(const std::string& /* h3Index */)>&& func): _function(std::make_unique<std::function<void(const std::string& /* h3Index */)>>(std::move(func))) {}
    inline void call(std::string h3Index) const noexcept {
      _function->operator()(h3Index);
    }
  private:
    std::unique_ptr<std::function<void(const std::string& /* h3Index */)>> _function;
  } SWIFT_NONCOPYABLE;
  Func_void_std__string create_Func_void_std__string(void* NON_NULL swiftClosureWrapper) noexcept;
  inline Func_void_std__string_Wrapper wrap_Func_void_std__string(Func_void_std__string value) noexcept {
    return Func_void_std__string_Wrapper(std::move(value));
  }
  
  // pragma MARK: std::vector<std::string>
  /**
   * Specialized version of `std::vector<std::string>`.
   */
  using std__vector_std__string_ = std::vector<std::string>;
  inline std::vector<std::string> create_std__vector_std__string_(size_t size) noexcept {
    std::vector<std::string> vector;
    vector.reserve(size);
    return vector;
  }
  
  // pragma MARK: std::shared_ptr<HybridHybridTrackingSpec>
  /**
   * Specialized version of `std::shared_ptr<HybridHybridTrackingSpec>`.
   */
  using std__shared_ptr_HybridHybridTrackingSpec_ = std::shared_ptr<HybridHybridTrackingSpec>;
  std::shared_ptr<HybridHybridTrackingSpec> create_std__shared_ptr_HybridHybridTrackingSpec_(void* NON_NULL swiftUnsafePointer) noexcept;
  void* NON_NULL get_std__shared_ptr_HybridHybridTrackingSpec_(std__shared_ptr_HybridHybridTrackingSpec_ cppType);
  
  // pragma MARK: std::weak_ptr<HybridHybridTrackingSpec>
  using std__weak_ptr_HybridHybridTrackingSpec_ = std::weak_ptr<HybridHybridTrackingSpec>;
  inline std__weak_ptr_HybridHybridTrackingSpec_ weakify_std__shared_ptr_HybridHybridTrackingSpec_(const std::shared_ptr<HybridHybridTrackingSpec>& strong) noexcept { return strong; }
  
  // pragma MARK: Result<void>
  using Result_void_ = Result<void>;
  inline Result_void_ create_Result_void_() noexcept {
    return Result<void>::withValue();
  }
  inline Result_void_ create_Result_void_(const std::exception_ptr& error) noexcept {
    return Result<void>::withError(error);
  }
  
  // pragma MARK: Result<std::vector<std::string>>
  using Result_std__vector_std__string__ = Result<std::vector<std::string>>;
  inline Result_std__vector_std__string__ create_Result_std__vector_std__string__(const std::vector<std::string>& value) noexcept {
    return Result<std::vector<std::string>>::withValue(value);
  }
  inline Result_std__vector_std__string__ create_Result_std__vector_std__string__(const std::exception_ptr& error) noexcept {
    return Result<std::vector<std::string>>::withError(error);
  }

} // namespace margelo::nitro::hybridtracker::bridge::swift
