const fs = require('fs');
const path = require('path');

describe('Maestro Visual Regression', () => {
  it('home screen matches baseline', () => {
    // Read the screenshot generated by Maestro
    const screenshotPath = path.join(__dirname, '../.maestro/screenshots/home_screen.png');
    
    if (!fs.existsSync(screenshotPath)) {
      console.warn('Screenshot not found. Please run `npm run test:e2e:smoke` first.');
      return; // Skip test if screenshot doesn't exist yet
    }

    const image = fs.readFileSync(screenshotPath);

    // Compare with baseline
    // The first time this runs, it will create a baseline image in a __image_snapshots__ directory.
    expect(image).toMatchImageSnapshot({
      failureThreshold: 0.05,
      failureThresholdType: 'percent',
      customSnapshotIdentifier: 'home-screen-baseline',
    });
  });
});
