/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#import "OPSQLiteSpec.h"


namespace facebook::react {
  
    static facebook::jsi::Value __hostFunction_NativeOPSQLiteSpecJSI_install(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, BooleanKind, "install", @selector(install), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeOPSQLiteSpecJSI_moveAssetsDatabase(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, BooleanKind, "moveAssetsDatabase", @selector(moveAssetsDatabase:extension:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeOPSQLiteSpecJSI_getConstants(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, ObjectKind, "getConstants", @selector(getConstants), args, count);
    }

  NativeOPSQLiteSpecJSI::NativeOPSQLiteSpecJSI(const ObjCTurboModule::InitParams &params)
    : ObjCTurboModule(params) {
      
        methodMap_["install"] = MethodMetadata {0, __hostFunction_NativeOPSQLiteSpecJSI_install};
        
        
        methodMap_["moveAssetsDatabase"] = MethodMetadata {2, __hostFunction_NativeOPSQLiteSpecJSI_moveAssetsDatabase};
        
        
        methodMap_["getConstants"] = MethodMetadata {0, __hostFunction_NativeOPSQLiteSpecJSI_getConstants};
        
  }
} // namespace facebook::react
