/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#ifndef __cplusplus
#error This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
#endif
#import <Foundation/Foundation.h>
#import <RCTRequired/RCTRequired.h>
#import <RCTTypeSafety/RCTConvertHelpers.h>
#import <RCTTypeSafety/RCTTypedModuleConstants.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTCxxConvert.h>
#import <React/RCTManagedPointer.h>
#import <ReactCommon/RCTTurboModule.h>
#import <optional>
#import <vector>

namespace JS {
  namespace NativeOPSQLite {
    struct Constants {

      struct Builder {
        struct Input {
          RCTRequired<NSString *> IOS_DOCUMENT_PATH;
          RCTRequired<NSString *> IOS_LIBRARY_PATH;
          RCTRequired<NSString *> ANDROID_DATABASE_PATH;
          RCTRequired<NSString *> ANDROID_FILES_PATH;
          RCTRequired<NSString *> ANDROID_EXTERNAL_FILES_PATH;
        };

        /** Initialize with a set of values */
        Builder(const Input i);
        /** Initialize with an existing Constants */
        Builder(Constants i);
        /** Builds the object. Generally used only by the infrastructure. */
        NSDictionary *buildUnsafeRawValue() const { return _factory(); };
      private:
        NSDictionary *(^_factory)(void);
      };

      static Constants fromUnsafeRawValue(NSDictionary *const v) { return {v}; }
      NSDictionary *unsafeRawValue() const { return _v; }
    private:
      Constants(NSDictionary *const v) : _v(v) {}
      NSDictionary *_v;
    };
  }
}
@protocol NativeOPSQLiteSpec <RCTBridgeModule, RCTTurboModule>

- (NSNumber *)install;
- (NSNumber *)moveAssetsDatabase:(NSString *)name
                       extension:(NSString *)extension;
- (facebook::react::ModuleConstants<JS::NativeOPSQLite::Constants::Builder>)constantsToExport;
- (facebook::react::ModuleConstants<JS::NativeOPSQLite::Constants::Builder>)getConstants;

@end
namespace facebook::react {
  /**
   * ObjC++ class for module 'NativeOPSQLite'
   */
  class JSI_EXPORT NativeOPSQLiteSpecJSI : public ObjCTurboModule {
  public:
    NativeOPSQLiteSpecJSI(const ObjCTurboModule::InitParams &params);
  };
} // namespace facebook::react
inline JS::NativeOPSQLite::Constants::Builder::Builder(const Input i) : _factory(^{
  NSMutableDictionary *d = [NSMutableDictionary new];
  auto IOS_DOCUMENT_PATH = i.IOS_DOCUMENT_PATH.get();
  d[@"IOS_DOCUMENT_PATH"] = IOS_DOCUMENT_PATH;
  auto IOS_LIBRARY_PATH = i.IOS_LIBRARY_PATH.get();
  d[@"IOS_LIBRARY_PATH"] = IOS_LIBRARY_PATH;
  auto ANDROID_DATABASE_PATH = i.ANDROID_DATABASE_PATH.get();
  d[@"ANDROID_DATABASE_PATH"] = ANDROID_DATABASE_PATH;
  auto ANDROID_FILES_PATH = i.ANDROID_FILES_PATH.get();
  d[@"ANDROID_FILES_PATH"] = ANDROID_FILES_PATH;
  auto ANDROID_EXTERNAL_FILES_PATH = i.ANDROID_EXTERNAL_FILES_PATH.get();
  d[@"ANDROID_EXTERNAL_FILES_PATH"] = ANDROID_EXTERNAL_FILES_PATH;
  return d;
}) {}
inline JS::NativeOPSQLite::Constants::Builder::Builder(Constants i) : _factory(^{
  return i.unsafeRawValue();
}) {}
