///
/// FogOfWburgAutolinking.mm
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#import <Foundation/Foundation.h>
#import <NitroModules/HybridObjectRegistry.hpp>
#import "FogOfWburg-Swift-Cxx-Umbrella.hpp"
#import <type_traits>

#include "HybridHybridTrackingSpecSwift.hpp"

@interface FogOfWburgAutolinking : NSObject
@end

@implementation FogOfWburgAutolinking

+ (void) load {
  using namespace margelo::nitro;
  using namespace margelo::nitro::hybridtracker;

  HybridObjectRegistry::registerHybridObjectConstructor(
    "HybridTracking",
    []() -> std::shared_ptr<HybridObject> {
      std::shared_ptr<HybridHybridTrackingSpec> hybridObject = FogOfWburg::FogOfWburgAutolinking::createHybridTracking();
      return hybridObject;
    }
  );
}

@end
