/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "NitroModulesSpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeNitroModulesCxxSpecJSI_install(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  auto result = static_cast<NativeNitroModulesCxxSpecJSI *>(&turboModule)->install(
    rt
  );
  return result ? jsi::Value(std::move(*result)) : jsi::Value::null();
}

NativeNitroModulesCxxSpecJSI::NativeNitroModulesCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("NitroModules", jsInvoker) {
  methodMap_["install"] = MethodMetadata {0, __hostFunction_NativeNitroModulesCxxSpecJSI_install};
}


} // namespace facebook::react
