/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include <react/bridging/Bridging.h>

namespace facebook::react {


  class JSI_EXPORT NativeOPSQLiteCxxSpecJSI : public TurboModule {
protected:
  NativeOPSQLiteCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker);

public:
  virtual jsi::Object getConstants(jsi::Runtime &rt) = 0;
  virtual bool install(jsi::Runtime &rt) = 0;
  virtual bool moveAssetsDatabase(jsi::Runtime &rt, jsi::String name, jsi::String extension) = 0;

};

template <typename T>
class JSI_EXPORT NativeOPSQLiteCxxSpec : public TurboModule {
public:
  jsi::Value get(jsi::Runtime &rt, const jsi::PropNameID &propName) override {
    return delegate_.get(rt, propName);
  }

  static constexpr std::string_view kModuleName = "OPSQLite";

protected:
  NativeOPSQLiteCxxSpec(std::shared_ptr<CallInvoker> jsInvoker)
    : TurboModule(std::string{NativeOPSQLiteCxxSpec::kModuleName}, jsInvoker),
      delegate_(reinterpret_cast<T*>(this), jsInvoker) {}

private:
  class Delegate : public NativeOPSQLiteCxxSpecJSI {
  public:
    Delegate(T *instance, std::shared_ptr<CallInvoker> jsInvoker) :
      NativeOPSQLiteCxxSpecJSI(std::move(jsInvoker)), instance_(instance) {}

    jsi::Object getConstants(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::getConstants) == 1,
          "Expected getConstants(...) to have 1 parameters");

      return bridging::callFromJs<jsi::Object>(
          rt, &T::getConstants, jsInvoker_, instance_);
    }
    bool install(jsi::Runtime &rt) override {
      static_assert(
          bridging::getParameterCount(&T::install) == 1,
          "Expected install(...) to have 1 parameters");

      return bridging::callFromJs<bool>(
          rt, &T::install, jsInvoker_, instance_);
    }
    bool moveAssetsDatabase(jsi::Runtime &rt, jsi::String name, jsi::String extension) override {
      static_assert(
          bridging::getParameterCount(&T::moveAssetsDatabase) == 3,
          "Expected moveAssetsDatabase(...) to have 3 parameters");

      return bridging::callFromJs<bool>(
          rt, &T::moveAssetsDatabase, jsInvoker_, instance_, std::move(name), std::move(extension));
    }

  private:
    T *instance_;
  };

  Delegate delegate_;
};

} // namespace facebook::react
