/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "OPSQLiteSpecJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeOPSQLiteCxxSpecJSI_getConstants(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeOPSQLiteCxxSpecJSI *>(&turboModule)->getConstants(
    rt
  );
}
static jsi::Value __hostFunction_NativeOPSQLiteCxxSpecJSI_install(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeOPSQLiteCxxSpecJSI *>(&turboModule)->install(
    rt
  );
}
static jsi::Value __hostFunction_NativeOPSQLiteCxxSpecJSI_moveAssetsDatabase(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeOPSQLiteCxxSpecJSI *>(&turboModule)->moveAssetsDatabase(
    rt,
    args[0].asString(rt),
    args[1].asString(rt)
  );
}

NativeOPSQLiteCxxSpecJSI::NativeOPSQLiteCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("OPSQLite", jsInvoker) {
  methodMap_["getConstants"] = MethodMetadata {0, __hostFunction_NativeOPSQLiteCxxSpecJSI_getConstants};
  methodMap_["install"] = MethodMetadata {0, __hostFunction_NativeOPSQLiteCxxSpecJSI_install};
  methodMap_["moveAssetsDatabase"] = MethodMetadata {2, __hostFunction_NativeOPSQLiteCxxSpecJSI_moveAssetsDatabase};
}


} // namespace facebook::react
