///
/// HybridHybridTrackingSpec_cxx.swift
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

import NitroModules

/**
 * A class implementation that bridges HybridHybridTrackingSpec over to C++.
 * In C++, we cannot use Swift protocols - so we need to wrap it in a class to make it strongly defined.
 *
 * Also, some Swift types need to be bridged with special handling:
 * - Enums need to be wrapped in Structs, otherwise they cannot be accessed bi-directionally (Swift bug: https://github.com/swiftlang/swift/issues/75330)
 * - Other HybridObjects need to be wrapped/unwrapped from the Swift TCxx wrapper
 * - Throwing methods need to be wrapped with a Result<T, Error> type, as exceptions cannot be propagated to C++
 */
open class HybridHybridTrackingSpec_cxx {
  /**
   * The Swift <> C++ bridge's namespace (`margelo::nitro::hybridtracker::bridge::swift`)
   * from `Derivee-Swift-Cxx-Bridge.hpp`.
   * This contains specialized C++ templates, and C++ helper functions that can be accessed from Swift.
   */
  public typealias bridge = margelo.nitro.hybridtracker.bridge.swift

  /**
   * Holds an instance of the `HybridHybridTrackingSpec` Swift protocol.
   */
  private var __implementation: any HybridHybridTrackingSpec

  /**
   * Holds a weak pointer to the C++ class that wraps the Swift class.
   */
  private var __cxxPart: bridge.std__weak_ptr_HybridHybridTrackingSpec_

  /**
   * Create a new `HybridHybridTrackingSpec_cxx` that wraps the given `HybridHybridTrackingSpec`.
   * All properties and methods bridge to C++ types.
   */
  public init(_ implementation: any HybridHybridTrackingSpec) {
    self.__implementation = implementation
    self.__cxxPart = .init()
    /* no base class */
  }

  /**
   * Get the actual `HybridHybridTrackingSpec` instance this class wraps.
   */
  @inline(__always)
  public func getHybridHybridTrackingSpec() -> any HybridHybridTrackingSpec {
    return __implementation
  }

  /**
   * Casts this instance to a retained unsafe raw pointer.
   * This acquires one additional strong reference on the object!
   */
  public func toUnsafe() -> UnsafeMutableRawPointer {
    return Unmanaged.passRetained(self).toOpaque()
  }

  /**
   * Casts an unsafe pointer to a `HybridHybridTrackingSpec_cxx`.
   * The pointer has to be a retained opaque `Unmanaged<HybridHybridTrackingSpec_cxx>`.
   * This removes one strong reference from the object!
   */
  public class func fromUnsafe(_ pointer: UnsafeMutableRawPointer) -> HybridHybridTrackingSpec_cxx {
    return Unmanaged<HybridHybridTrackingSpec_cxx>.fromOpaque(pointer).takeRetainedValue()
  }

  /**
   * Gets (or creates) the C++ part of this Hybrid Object.
   * The C++ part is a `std::shared_ptr<HybridHybridTrackingSpec>`.
   */
  public func getCxxPart() -> bridge.std__shared_ptr_HybridHybridTrackingSpec_ {
    let cachedCxxPart = self.__cxxPart.lock()
    if Bool(fromCxx: cachedCxxPart) {
      return cachedCxxPart
    } else {
      let newCxxPart = bridge.create_std__shared_ptr_HybridHybridTrackingSpec_(self.toUnsafe())
      __cxxPart = bridge.weakify_std__shared_ptr_HybridHybridTrackingSpec_(newCxxPart)
      return newCxxPart
    }
  }

  

  /**
   * Get the memory size of the Swift class (plus size of any other allocations)
   * so the JS VM can properly track it and garbage-collect the JS object if needed.
   */
  @inline(__always)
  public var memorySize: Int {
    return MemoryHelper.getSizeOf(self.__implementation) + self.__implementation.memorySize
  }

  /**
   * Compares this object with the given [other] object for reference equality.
   */
  @inline(__always)
  public func equals(other: HybridHybridTrackingSpec_cxx) -> Bool {
    return self.__implementation === other.__implementation
  }

  /**
   * Call dispose() on the Swift class.
   * This _may_ be called manually from JS.
   */
  @inline(__always)
  public func dispose() {
    self.__implementation.dispose()
  }

  /**
   * Call toString() on the Swift class.
   */
  @inline(__always)
  public func toString() -> String {
    return self.__implementation.toString()
  }

  // Properties
  

  // Methods
  @inline(__always)
  public final func startTracking() -> bridge.Result_void_ {
    do {
      try self.__implementation.startTracking()
      return bridge.create_Result_void_()
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_void_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func stopTracking() -> bridge.Result_void_ {
    do {
      try self.__implementation.stopTracking()
      return bridge.create_Result_void_()
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_void_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func addListener(callback: bridge.Func_void_std__string) -> bridge.Result_void_ {
    do {
      try self.__implementation.addListener(callback: { () -> (String) -> Void in
        let __wrappedFunction = bridge.wrap_Func_void_std__string(callback)
        return { (__h3Index: String) -> Void in
          __wrappedFunction.call(std.string(__h3Index))
        }
      }())
      return bridge.create_Result_void_()
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_void_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func removeListener() -> bridge.Result_void_ {
    do {
      try self.__implementation.removeListener()
      return bridge.create_Result_void_()
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_void_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getDiscoveredHexesSince(timestamp: Double) -> bridge.Result_std__vector_std__string__ {
    do {
      let __result = try self.__implementation.getDiscoveredHexesSince(timestamp: timestamp)
      let __resultCpp = { () -> bridge.std__vector_std__string_ in
        var __vector = bridge.create_std__vector_std__string_(__result.count)
        for __item in __result {
          __vector.push_back(std.string(__item))
        }
        return __vector
      }()
      return bridge.create_Result_std__vector_std__string__(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__vector_std__string__(__exceptionPtr)
    }
  }
}
