///
/// DeriveeAutolinking.mm
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#import <Foundation/Foundation.h>
#import <NitroModules/HybridObjectRegistry.hpp>
#import "Derivee-Swift-Cxx-Umbrella.hpp"
#import <type_traits>

#include "HybridHybridTrackingSpecSwift.hpp"

@interface DeriveeAutolinking : NSObject
@end

@implementation DeriveeAutolinking

+ (void) load {
  using namespace margelo::nitro;
  using namespace margelo::nitro::hybridtracker;

  HybridObjectRegistry::registerHybridObjectConstructor(
    "HybridTracking",
    []() -> std::shared_ptr<HybridObject> {
      std::shared_ptr<HybridHybridTrackingSpec> hybridObject = Derivee::DeriveeAutolinking::createHybridTracking();
      return hybridObject;
    }
  );
}

@end
