///
/// hybrid_tracker-Swift-Cxx-Umbrella.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

// Forward declarations of C++ defined types
// Forward declaration of `HybridHybridTrackingSpec` to properly resolve imports.
namespace margelo::nitro::hybridtracker { class HybridHybridTrackingSpec; }

// Include C++ defined types
#include "HybridHybridTrackingSpec.hpp"
#include <NitroModules/Result.hpp>
#include <exception>
#include <functional>
#include <memory>
#include <string>
#include <vector>

// C++ helpers for Swift
#include "hybrid_tracker-Swift-Cxx-Bridge.hpp"

// Common C++ types used in Swift
#include <NitroModules/ArrayBufferHolder.hpp>
#include <NitroModules/AnyMapUtils.hpp>
#include <NitroModules/RuntimeError.hpp>
#include <NitroModules/DateToChronoDate.hpp>

// Forward declarations of Swift defined types
// Forward declaration of `HybridHybridTrackingSpec_cxx` to properly resolve imports.
namespace hybrid_tracker { class HybridHybridTrackingSpec_cxx; }

// Include Swift defined types
#if __has_include("hybrid_tracker-Swift.h")
// This header is generated by Xcode/Swift on every app build.
// If it cannot be found, make sure the Swift module's name (= podspec name) is actually "hybrid_tracker".
#include "hybrid_tracker-Swift.h"
// Same as above, but used when building with frameworks (`use_frameworks`)
#elif __has_include(<hybrid_tracker/hybrid_tracker-Swift.h>)
#include <hybrid_tracker/hybrid_tracker-Swift.h>
#else
#error hybrid_tracker's autogenerated Swift header cannot be found! Make sure the Swift module's name (= podspec name) is actually "hybrid_tracker", and try building the app first.
#endif
