///
/// hybrid_tracker-Swift-Cxx-Bridge.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#include "hybrid_tracker-Swift-Cxx-Bridge.hpp"

// Include C++ implementation defined types
#include "HybridHybridTrackingSpecSwift.hpp"
#include "hybrid_tracker-Swift-Cxx-Umbrella.hpp"
#include <NitroModules/NitroDefines.hpp>

namespace margelo::nitro::hybridtracker::bridge::swift {

  // pragma MARK: std::function<void(const std::string& /* h3Index */)>
  Func_void_std__string create_Func_void_std__string(void* NON_NULL swiftClosureWrapper) noexcept {
    auto swiftClosure = hybrid_tracker::Func_void_std__string::fromUnsafe(swiftClosureWrapper);
    return [swiftClosure = std::move(swiftClosure)](const std::string& h3Index) mutable -> void {
      swiftClosure.call(h3Index);
    };
  }
  
  // pragma MARK: std::shared_ptr<HybridHybridTrackingSpec>
  std::shared_ptr<HybridHybridTrackingSpec> create_std__shared_ptr_HybridHybridTrackingSpec_(void* NON_NULL swiftUnsafePointer) noexcept {
    hybrid_tracker::HybridHybridTrackingSpec_cxx swiftPart = hybrid_tracker::HybridHybridTrackingSpec_cxx::fromUnsafe(swiftUnsafePointer);
    return std::make_shared<margelo::nitro::hybridtracker::HybridHybridTrackingSpecSwift>(swiftPart);
  }
  void* NON_NULL get_std__shared_ptr_HybridHybridTrackingSpec_(std__shared_ptr_HybridHybridTrackingSpec_ cppType) {
    std::shared_ptr<margelo::nitro::hybridtracker::HybridHybridTrackingSpecSwift> swiftWrapper = std::dynamic_pointer_cast<margelo::nitro::hybridtracker::HybridHybridTrackingSpecSwift>(cppType);
    #ifdef NITRO_DEBUG
    if (swiftWrapper == nullptr) [[unlikely]] {
      throw std::runtime_error("Class \"HybridHybridTrackingSpec\" is not implemented in Swift!");
    }
    #endif
    hybrid_tracker::HybridHybridTrackingSpec_cxx& swiftPart = swiftWrapper->getSwiftPart();
    return swiftPart.toUnsafe();
  }

} // namespace margelo::nitro::hybridtracker::bridge::swift
