///
/// HybridHybridTrackingSpec.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#include "HybridHybridTrackingSpec.hpp"

namespace margelo::nitro::hybridtracker {

  void HybridHybridTrackingSpec::loadHybridMethods() {
    // load base methods/properties
    HybridObject::loadHybridMethods();
    // load custom methods/properties
    registerHybrids(this, [](Prototype& prototype) {
      prototype.registerHybridMethod("startTracking", &HybridHybridTrackingSpec::startTracking);
      prototype.registerHybridMethod("stopTracking", &HybridHybridTrackingSpec::stopTracking);
      prototype.registerHybridMethod("addListener", &HybridHybridTrackingSpec::addListener);
      prototype.registerHybridMethod("removeListener", &HybridHybridTrackingSpec::removeListener);
      prototype.registerHybridMethod("getDiscoveredHexesSince", &HybridHybridTrackingSpec::getDiscoveredHexesSince);
    });
  }

} // namespace margelo::nitro::hybridtracker
