///
/// HybridHybridTrackingSpec.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

#if __has_include(<NitroModules/HybridObject.hpp>)
#include <NitroModules/HybridObject.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif



#include <string>
#include <functional>
#include <vector>

namespace margelo::nitro::hybridtracker {

  using namespace margelo::nitro;

  /**
   * An abstract base class for `HybridTracking`
   * Inherit this class to create instances of `HybridHybridTrackingSpec` in C++.
   * You must explicitly call `HybridObject`'s constructor yourself, because it is virtual.
   * @example
   * ```cpp
   * class HybridHybridTracking: public HybridHybridTrackingSpec {
   * public:
   *   HybridHybridTracking(...): HybridObject(TAG) { ... }
   *   // ...
   * };
   * ```
   */
  class HybridHybridTrackingSpec: public virtual HybridObject {
    public:
      // Constructor
      explicit HybridHybridTrackingSpec(): HybridObject(TAG) { }

      // Destructor
      ~HybridHybridTrackingSpec() override = default;

    public:
      // Properties
      

    public:
      // Methods
      virtual void startTracking() = 0;
      virtual void stopTracking() = 0;
      virtual void addListener(const std::function<void(const std::string& /* h3Index */)>& callback) = 0;
      virtual void removeListener() = 0;
      virtual std::vector<std::string> getDiscoveredHexesSince(double timestamp) = 0;

    protected:
      // Hybrid Setup
      void loadHybridMethods() override;

    protected:
      // Tag for logging
      static constexpr auto TAG = "HybridTracking";
  };

} // namespace margelo::nitro::hybridtracker
